### ISSUE TITLE
Asteroiden Sichtweite ;)

### ISSUE THREAD

**Issue by Benman2785** [Nos-Fi/HC-Mod#11]
Hi, ich zocke zwar nur noch selten auf HHC - aber hier mal ein Mod den ich auf meinem Server ähnlich am laufen habe ;)
[script.txt](https://github.com/Nos-Fi/HC-Mod/files/8257875/script.txt)

**Comment by Benman2785** [comment]
außerdem wäre der Spinning Planets Mod (Gibbons spinning planet mod reduced to XML by Thaddeus 13-7-2005, Fuji fix added 25-8-05) ne geile Sache für den HHC - aber es muss dann noch ne dll geändert werden damit die Planeten nicht langsamer oder schneller werden

**Comment by Benman2785** [comment]
[engine_equip.txt](https://github.com/Nos-Fi/HC-Mod/files/8257892/engine_equip.txt)

damit fliegen die Schiffe unterschiedlich schnell ;)

**Comment by Nos-Fi** [comment]
Zu Asteroiden: wir haben ja auch schon erhöhte details bei Asteroiden auf HHC. Wirkt sich das dann eh nicht zu heftig aus wenn man die Sichtbarkeit so erhöht?

Zu Spinning planets: gibts ja schon lange hab's mir ehrlich gesagt noch nie in-game angesehen

Zu engine equip:
Bei uns kann man ja die Antriebe frei wechseln. Das müsste man dafür rückgängig machen oder

**Comment by Benman2785** [comment]
rein der Theorie sollte man mit den jeweiligen Antrieben dann auch unterschiedliche Geschwindkeiten haben ;)

Spinning Planets - besonders mit HD Mod sieht echt gut aus und gibt einen Realismus-Kick.

wie verändert ihr die sichtweite? bin mit meinem Mod noch nicht 100% glücklich - die Asteroiden ploppen dann bei der entfernung auf - hätte sie gern dauerhaft in sicht (was mit meiner version dann performance probleme zwecks game-engine-limits erzeugt)

**Comment by Benman2785** [comment]
ps man ändert nur den CruiseSpeed in der ini und muss die DLL einfügen

cruise_speed = 285.1
dann fliegt das Schiff mit 285
max ist 500 - mehr zeigt der Mod der dll nicht richtig an - aber so kann man bissl was basteln
hab es in meinem Mod - und die wenigen die auf meinem Server sind finden das feature am besten

**Comment by Nos-Fi** [comment]
Denke nicht dass wir das jemals noch einbauen.
